### ISSUE TITLE
FTweaks incompatibility w/Angel's Refining

### ISSUE THREAD

**Issue by Baughn** [Arch666Angel/angelsrefining#2]
And I'm pretty sure it's your fault, sorry. :)

The problem occurs with only those two mods activated. (And also with a lot more mods active.)

`__FTweaks__/data-updates.lua:3: __FTweaks__/prototypes/advanced-satellite.lua:16: bad argument #1 to 'find' (string expected, got nil)`

The code in question looks like this:
```
require "functions"

if Config.advancedSatellite then

local recipe = table.deepcopy(data.raw.recipe.satellite)
local ingredients = {}
for _,ingredient in pairs(recipe.ingredients) do
	ingredient = table.deepcopy(ingredient)
	log("Parsing ingredient: " .. (ingredient[1] and ingredient[1] or "nil") .. " x " .. (ingredient[2] and ingredient[2] or "nil"))
	if ingredient[1] == "plutonium" then
		ingredient[2] = 10
	end
	if ingredient[1] == "processing-unit" then
		ingredient[1] = "advanced-circuit"
	end
	if string.find(ingredient[1], "accumulator") or string.find(ingredient[1], "solar-panel", 1, true) then
		ingredient[2] = ingredient[2]*2
	end
	if ingredient[1] == "radar" or ingredient[1] == "rocket-fuel" or ingredient[1] == "low-density-structure" then
		ingredient[2] = 0
	end
	if ingredient[2] > 0 then
		table.insert(ingredients, ingredient)
	end
end
```

So it seems like Angel's Refining is inserting `nil` into the ingredient list, which can't possibly be valid. I don't see any references to satellites in your mod, but you know it better than I.

Pinging @ReikaKalseki as a courtesy, because there's code here to handle this case (for the logging), but it isn't protecting the rest of the code.

**Comment by Baughn** [comment]
Disabling the advanced research satellite (in FTweaks) does function as a workaround.

**Comment by Arch666Angel** [comment]
Well it kinda is a mix of fail on both sides, there is a part in the override functions that will convert recipes to use the normal/expensive layout, so it is recipe.normal.ingredients and recipe.expensive.ingredients then instead of recipe.ingredients. That's probably where the error comes from. So I have to pass the ball back to @ReikaKalseki then that he adds a check for that to his function.

if not recipe.ingredients then
  if recipe.normal.ingredients then
  bla bla recipe.expensive.ingredients = recipe.normal.ingredients
  end
end

something along the line, or convert it to use the normal/expensive scheme as a whole, which makes more sense, but is also more work.

**Comment by ReikaKalseki** [comment]
> Well it kinda is a mix of fail on both sides, there is a part in the override functions that will convert recipes to use the normal/expensive layout, so it is recipe.normal.ingredients and recipe.expensive.ingredients then instead of recipe.ingredients. That's probably where the error comes from. So I have to pass the ball back to @ReikaKalseki then that he adds a check for that to his function.

That does not explain having a nonnull array but still containing null entries. *That* is invalid. I can - and probably should - handle recipe variants, but recipes of *null* is something that should not be tolerated.

Also, for the record, TextPlates has the same issue. Why that mod is editing the satellite recipe I have no idea.

**Comment by Arch666Angel** [comment]
I cant say for sure what is going on, because I dont do any direct changes to the satellite recipe. It might be affected to global changes to some degree, but they shouldnt change the general recipe layout as is.

If you use normal/expensive the engine will just delete recipe.ingredients, that's why it's nil and that's why it's no longer avaible. But as I said only a guess what is happening there. I'll check with Exasperation who maintains the override function code if there is anything an our side going wrong there.

**Comment by ReikaKalseki** [comment]
> the engine will just delete recipe.ingredients, that's why it's nil and that's why it's no longer avaible

Again, that is not what is happening. `recipe.ingredients != nil`, `recipe.ingredients = [*, *, nil, *, ...]`.

**Comment by Arch666Angel** [comment]
Well then I assume the problem is not on my side, because that is the only case I can imagine to happen. As I said I dont do direct changes to the satellite recipe, so I guess it's about improving the code on your side then.

**Comment by ReikaKalseki** [comment]
> I guess it's about improving the code on your side then

I have a longstanding and rigid policy of not accommodating for serious errors; that only masks them and leaves them to go unfixed for extended periods of time.

**Comment by Nexela** [comment]
ingredients have 2 valid forms

{"name", amount} or {name = "name",  amount = amount, type = "type" ...(a couple other things)}
ingredient[1] only works in the first case, it will be nil in the second case. Failure to check ingredient[1] OR ingredient.name is the problem here.

**Comment by ReikaKalseki** [comment]
And *that* could be caused by an automated trawler. @Baughn Can you forward this to my issue tracker?

**Comment by Baughn** [comment]
Done.

**Comment by Arch666Angel** [comment]
Well that sure is caused by someone changing the recipe format, but then that's still valid and a matter of you not checking for these cases. I consider this closed.
